### ISSUE TITLE
Just a quick question 

### ISSUE THREAD

**Issue by XxHailHydraxX** [Proxysec/dorKer#2]
Whats up with the syntax and format unable to get the  script to run without tromping error now i can compile it to exe and it runs fine but i prefer the py script instead :)

it could be me messing something up.. just taking it that it was built for exe or was code from a different langue and was translated 

anyways thanks for your time

**Comment by Proxysec** [comment]
Oh sorry, when i was copying the src ig it did not format correctly i will try and reformat it

**Comment by XxHailHydraxX** [comment]
Thank you very much For the Reply
